name = "ProbabilisticGrammars"
uuid = "1b43da28-524a-4f20-8d05-801d6b3064eb"
authors = ["Daniel Harasim <dr.dharasim@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
